### ISSUE TITLE
bonk_addresses defined outside of patch_rom

### ISSUE THREAD

**Issue by StructuralMike** [Berserker66/MultiWorld-Utilities#176]
In Rom.py the bonk_addresses variable is defined outside of the patch_rom() function so if "b" prize shuffle is not turned on, it is not defined:

```
  File "Rom.py", line 1112, in patch_rom
    for address in bonk_addresses:
UnboundLocalError: local variable 'bonk_addresses' referenced before assignment
```

I'm not entirely sure why it still works on the main branch and not in my experimental, but I fixed this by moving the bonk_addresses to before the 'if "b" rather than outside the function - which seems like a good idea anyway, which is why I submitted this issue.

**Comment by Berserker66** [comment]
The reason it is defined globally is so that it is shared between threads; patch_rom() is called from a thread pool and creating it in each thread would create and later destroy a copy in each thread, instead of one instance that gets re-used.

From the error message I can tell that you bind the name "bonk_addresses" locally in that function, which makes the interpreter ignore the global variable. You can "fix" this by writing `global bonk_addresses` as the first line of the function definition.
