### ISSUE TITLE
Entrance rando removes silvers when swordless and hard/expert pool are set

### ISSUE THREAD

**Issue by adilor18** [Berserker66/MultiWorld-Utilities#67]
This has been raised several times on the main github, but Berserker told me during a multi to submit it here, so here I am.

When running the entrance randomizer, and swordless and hard/expert pool are set, the logically-hard-required silvers end up removed. This does apply to multi as well; I experienced it personally by way of receiving a green 20 in place of the second progressive bow when it was sent to me.

My understanding, from reading descriptions by others who are more familiar with the code than I, is that it's something to do with the patch order. The interaction of swordless and hard/expert happens correctly, but then entrance comes in, sees the pool setting, and strips the silvers. This results in an effectively unwinnable seed.

**Comment by Berserker66** [comment]
Yeah, I don't know enough about the baserom asm to figure out where it is going wrong. I can tell someone already tried to fix it. Relevant bits from rom.py:
```
    #Work around for json patch ordering issues - write bow limit separately so that it is replaced in the patch
    rom.write_bytes(0x180098, [difficulty.progressive_bow_limit, overflow_replacement])

    if difficulty.progressive_bow_limit < 2 and world.swords[player] == 'swordless':
        rom.write_bytes(0x180098, [2, overflow_replacement])
        rom.write_byte(0x180181, 0x01) # Make silver arrows work only on ganon
        rom.write_byte(0x180182, 0x00) # Don't auto equip silvers on pickup
```
^ That if gets triggered. It might just be missing flags. overflow replacement is 20 rupees, this might need to put the bow back in instead of rupees. Would need to try tinkering with it

**Comment by Berserker66** [comment]
Further checking shows, that this is where 
```
    #Work around for json patch ordering issues - write bow limit separately so that it is replaced in the patch
    rom.write_bytes(0x180098, [difficulty.progressive_bow_limit, overflow_replacement])
```
came from in the first place, so that won't solve anything.

**Comment by compiling** [comment]
That line was solving an issue where the json rom contained 0x180098 = 1, and also 0x180098 = 2.  And then on python 3.5 and below, the order of the patch was non-deterministic and the flag would end up as 1.  The flag at 0x180098 is the number of bows you're allowed to collect.

So I would have expected this to be fixed in Multiworld Utils 1.9, and in previous versions to only affect hard / swordless / enemizer (including sprite changing) generated with python 3.5 and below.

If that's not the case, then there's another bug with the bow limit and hopefully a way to replicate it.

**Comment by Berserker66** [comment]
Utils 1.9 only supports Python 3.7 and up. Annotations features are used that got introduced with 3.7

**Comment by compiling** [comment]
Ok, so as an update that seed was generated with Multiworld Utils 1.8 which means that it doesn't have the json patch fix.  It might still be another issue though, especially if the 2nd bow doesn't appear in the spoiler log.

**Comment by adilor18** [comment]
I'm happy to report that a run of similar settings on the current release did not produce the issue. I was able to collect the silvers (in tile room after collecting somaria in DM room, no less) and utilize them against Ganon.

[ER_M482833355_Spoiler.txt](https://github.com/Berserker66/MultiWorld-Utilities/files/4495901/ER_M482833355_Spoiler.txt)
[ER_M482833355.zip](https://github.com/Berserker66/MultiWorld-Utilities/files/4495902/ER_M482833355.zip)

**Comment by Berserker66** [comment]
Hm. I'll have to check non-progressive again then, it might spawn two instances of Bow and none of Silvers, which would explain why I didn't see them in my tests. As I was also looking for Progressive Bow (Alt), which is missing from the progressive log.

**Comment by Berserker66** [comment]
This seems to be fixed. Should someone encounter this again on newer versions just open a new issue with a spoiler log please.
